layout_spectrum: 0.5162907
color:
  saturation: 0.5839599
  lightness: 0.3333333
  brandStrength: 1
  brandColors:
    - '#4C4A4B'
    - '#201816'
    - '#DCDE57'
    - '#ACAD38'
    - '#848527'
  rhythmicContrast: 0.656015
typography_spectrum: 0.4605263
name: 'IreneOleksiuk '
